// Generated by `npm run cf-typegen`. Update when bindings change.
export interface Env {
  NODE_ENV: string
  STEPINTOVISION_CATALOG?: string
  STEPINTOVISION_CATALOG_KV?: STEPINTOVISION_CATALOG_KV
}
